// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.3
// source: mcache.proto

package mcache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_OK        Status = 0
	Status_NOT_FOUND Status = 1
	Status_STORE_ERR Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OK",
		1: "NOT_FOUND",
		2: "STORE_ERR",
	}
	Status_value = map[string]int32{
		"OK":        0,
		"NOT_FOUND": 1,
		"STORE_ERR": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_mcache_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_mcache_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_mcache_proto_rawDescGZIP(), []int{0}
}

type Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stat    Status `protobuf:"varint,2,opt,name=stat,proto3,enum=mcache.Status" json:"stat,omitempty"`
	Key     string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Ctype   string `protobuf:"bytes,4,opt,name=ctype,proto3" json:"ctype,omitempty"`
	Mtime   int64  `protobuf:"varint,5,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Content []byte `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Size    int64  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *Entry) Reset() {
	*x = Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mcache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_mcache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_mcache_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetStat() Status {
	if x != nil {
		return x.Stat
	}
	return Status_OK
}

func (x *Entry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Entry) GetCtype() string {
	if x != nil {
		return x.Ctype
	}
	return ""
}

func (x *Entry) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *Entry) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Entry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_mcache_proto protoreflect.FileDescriptor

var file_mcache_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x22, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e,
	0x2e, 0x6d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x04,
	0x73, 0x74, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x74, 0x69,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x2a, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10,
	0x01, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x54, 0x4f, 0x52, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x10, 0x02,
	0x32, 0x7c, 0x0a, 0x05, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x25, 0x0a, 0x03, 0x47, 0x65, 0x74,
	0x12, 0x0d, 0x2e, 0x6d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x1a,
	0x0d, 0x2e, 0x6d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x00,
	0x12, 0x25, 0x0a, 0x03, 0x50, 0x75, 0x74, 0x12, 0x0d, 0x2e, 0x6d, 0x63, 0x61, 0x63, 0x68, 0x65,
	0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x1a, 0x0d, 0x2e, 0x6d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x12, 0x0d,
	0x2e, 0x6d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x1a, 0x0d, 0x2e,
	0x6d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x00, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2f, 0x6d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_mcache_proto_rawDescOnce sync.Once
	file_mcache_proto_rawDescData = file_mcache_proto_rawDesc
)

func file_mcache_proto_rawDescGZIP() []byte {
	file_mcache_proto_rawDescOnce.Do(func() {
		file_mcache_proto_rawDescData = protoimpl.X.CompressGZIP(file_mcache_proto_rawDescData)
	})
	return file_mcache_proto_rawDescData
}

var file_mcache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcache_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mcache_proto_goTypes = []interface{}{
	(Status)(0),   // 0: mcache.status
	(*Entry)(nil), // 1: mcache.Entry
}
var file_mcache_proto_depIdxs = []int32{
	0, // 0: mcache.Entry.stat:type_name -> mcache.status
	1, // 1: mcache.Cache.Get:input_type -> mcache.Entry
	1, // 2: mcache.Cache.Put:input_type -> mcache.Entry
	1, // 3: mcache.Cache.Del:input_type -> mcache.Entry
	1, // 4: mcache.Cache.Get:output_type -> mcache.Entry
	1, // 5: mcache.Cache.Put:output_type -> mcache.Entry
	1, // 6: mcache.Cache.Del:output_type -> mcache.Entry
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mcache_proto_init() }
func file_mcache_proto_init() {
	if File_mcache_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mcache_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mcache_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcache_proto_goTypes,
		DependencyIndexes: file_mcache_proto_depIdxs,
		EnumInfos:         file_mcache_proto_enumTypes,
		MessageInfos:      file_mcache_proto_msgTypes,
	}.Build()
	File_mcache_proto = out.File
	file_mcache_proto_rawDesc = nil
	file_mcache_proto_goTypes = nil
	file_mcache_proto_depIdxs = nil
}
